.\" d64view man page, section 1
.\" $Id: d64view.1,v 1.2 2003/07/23 19:59:58 vividos Exp $
.\" 
.TH "d64view" 1
.SH NAME
d64view \- d64 disk image viewer
.SH SYNOPSIS
.B d64view
.SH DESCRIPTION
d64view shows d64 disk image contents, such as file directory, block
availability map and error codes. It handles several widely used disk
image formats, such as d64, d81, etc.
.SH BUGS
none known
.SH AUTHORS
Michael Fink <vividos at sourceforge dot net>
.SH NOTES
d64view is available here: 
.I http://www.vividos.de/

d64view (C) 2002,2003 Michael Fink

d64view is licensed under the GNU General Public License
